### ISSUE TITLE
Support JSON Output

### ISSUE THREAD

**Issue by joefitzgerald** [shurcooL/gostatus#28]
It would be great if this tool supported a flag for JSON output, so that other tools could reason over the results more easily.

**Comment by shurcooL** [comment]
I can definitely support that, it just needs a new [`Presenter` func](https://github.com/shurcooL/gostatus/blob/8d410b4b3025337ef08139296334baca2c597cfc/presenter.go#L9) and a flag to use it.

Can you think of what would be a good JSON scheme to output?

**Comment by shurcooL** [comment]
Perhaps I should use the actual `Repo` struct from https://github.com/shurcooL/gostatus/blob/8d410b4b3025337ef08139296334baca2c597cfc/repo.go?

**Comment by shurcooL** [comment]
How's this look like, @joefitzgerald?

```
gostatus $ gostatus github.com/shurcooL/gostatus
 *-  github.com/shurcooL/gostatus/...
gostatus $ gostatus -json github.com/shurcooL/gostatus
{"Path":"/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/shurcooL/gostatus","Root":"github.com/shurcooL/gostatus","DefaultBranch":"master","Local":{"RemoteURL":"https://github.com/shurcooL/gostatus","Status":" M main.go\n M presenter.go\n M repo.go\n M workspace.go\n","Branch":"master","Revision":"0086921ea1da30a4b840b8d3b0094e3eb261fade","Stash":""},"Remote":{"RepoURL":"https://github.com/shurcooL/gostatus","Revision":"8d410b4b3025337ef08139296334baca2c597cfc"},"LocalContainsRemoteRevision":true}
gostatus $ 
```

**Comment by joefitzgerald** [comment]
It could be as simple as:

```json
[
  {
    package: 'github.com/joefitzgerald/somepackage',
    status: 'outdated'
  },
  {
    package: 'github.com/joefitzgerald/someotherpackage',
    status: 'current'
  }
]
```

**Comment by shurcooL** [comment]
The difficulty with that is that a repository status can be in other states too. For example, imagine you have a `feature-foo` branch checked out, uncommitted changes in working directory, and there's an update available. Is it fair to say the "status" is "outdated"? Running `go get -u` wouldn't work because of non-standard branch and uncommitted changes, etc.

Maybe it'd be helpful if you could tell me how you want to use the output of `gostatus`.

**Comment by joefitzgerald** [comment]
Yeah, I can understand that. Mostly I'm interested in promoting someone to update the package via `go get -u github.com/joefitzgerald/somepackage` if the user's using a clean tree and on the default branch. Anything other than that is undefined and up to the user, IMO.

**Comment by shurcooL** [comment]
> Mostly I'm interested in prompting someone to update the package

In what context? Is it when they run your program, you want it to check for an updated version of itself?

**Comment by joefitzgerald** [comment]
Nope, I'm the author of [`go-plus`](https://atom.io/packages/go-plus); it makes use of a variety of tools, like gometalinter, gocode, goimports, etc, and I would like to notify the user when they are using an outdated version of those tools.

**Comment by shurcooL** [comment]
You could just execute `gostatus golang.org/x/tools/cmd/goimports` and check if the output starts with `"  + "`. But that'd be risky because the current gostatus output is meant to be read by humans, so it may change and break any machine attempt to read it. A previous generation version of gostatus used to have a -plumbing flag to output in a machine-readable, stable way.

So it seems for your needs, you want the JSON output to be equally high-level as the normal output, rather than the raw low-level repository data.

**Comment by shurcooL** [comment]
I'll close this since I don't see anything actionable for me to do here.

Please feel free to re-open if you think there's something to do, and describe it in concrete detail.

**Comment by shurcooL** [comment]
> Yeah, I can understand that. Mostly I'm interested in prompting someone to update the package via `go get -u github.com/joefitzgerald/somepackage` if the user's using a clean tree and on the default branch. Anything other than that is undefined and up to the user, IMO.

> a variety of tools, like gometalinter, gocode, goimports, etc, and I would like to notify the user when they are using an outdated version of those tools.

FWIW, I do something like that in Go-Package-Store to decide whether to present a Go repo as one that has updates available. You can see the code here:

https://github.com/shurcooL/Go-Package-Store/blob/7516406a51a34138ec20c6bf632fb479509da62c/main.go#L31-L54

It sounds like what you want is a CLI version of that?
