### ISSUE TITLE
Repo URLs should probably be compared with the protocol removed

### ISSUE THREAD

**Issue by siebenmann** [shurcooL/gostatus#30]
I tend to configure local copies of my own Github repos with the remote being `git@github.com:siebenmann/repo`, so that I push to Github via SSH. Right now this makes gostatus think that the remote path doesn't match the local path, since the official remote path it picks is `https://github.com/siebenmann/repo`. The best solution for this seems likely to be a protocol independent comparison of the remote path.

(By the way, thank you for gostatus. It's a great tool and a nice complement to Go-Package-Store.)

**Comment by shurcooL** [comment]
> (By the way, thank you for gostatus. It's a great tool and a nice complement to Go-Package-Store.)

Glad to hear that, thanks!

> Repo URLs should probably be compared with the protocol removed

This is a good point, thanks for raising it. I'd like to think about this and discuss it with you.

Are you familiar with the `-f` flag that `go get` offers as of a few versions ago?

[Its documentation](https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies):

> The -f flag, valid only when -u is set, forces get -u not to verify that each package has been checked out from the source control repository implied by its import path. This can be useful if the source is a local fork of the original.

You should look at the issue #24 where this functionality was first added to `gostatus`, specifically https://github.com/shurcooL/gostatus/issues/24#issuecomment-67449830.

So, `gostatus` currently supports `-f` which mimics the `go` tool. By using it, you can resolve your issue.

Can you try it and let me know what you think?

However, I understand there's possible room for improvement. Right now, the situation is there are two extremes. Either be very strict (no `-f` flag), or not check remotes at all (with `-f` flag). This has the benefit of being simple and mirroring what the `go` command does, but is it optimal? Maybe `gostatus` should do something in between, which is as you suggested:

> Repo URLs should probably be compared with the protocol removed

What do you think?

**Comment by siebenmann** [comment]
I think that `-f` is going too far for what I want because it suppresses all remote checks. I do want to know if a local repo's remote setting is (or has become) wrong for some reason.

It may be worth noting here that `go get -u` doesn't complain about my example repo setting difference. This behavior seems to be implied by the text in `go help importpath` about trying multiple schemes when the VCS supports them; if the VCS supports multiple access schemes, the scheme-specific repo names presumably must all be considered equivalent.

Given this `go get` behavior and that the go tooling provides no direct way of knowing whether `go get -u` will consider two repo URLs to be equivalent, I think that a protocol-less comparison is the most correct answer. I do think that `gostatus` should not complain if `go get -u` won't.

**Comment by shurcooL** [comment]
> I do think that gostatus should not complain if `go get -u` won't.

Agreed. I'll look into resolving this.

**Comment by shurcooL** [comment]
@siebenmann Sorry for the delay. I just got a chance to look at this.

I've done the following experiment.

I did `go get github.com/siebenmann/call` and it successfully placed it in my `GOPATH/src/github.com/siebenmann/call`.

Then I did `go get -u github.com/siebenmann/call` and it succeeded. Doing `gostatus` printed clean status, as expected.

Then I changed the remote URL from `https://github.com/siebenmann/call` to `git@github.com:siebenmann/call` and `gostatus` printed `#`, but `go get -u` worked without any warnings.

However, I then did something which is clearly invalid. I changed the remote URL to `https://gopkg.in/siebenmann/call.v0`. `gostatus` still printed `#` and I expected `go get -u` to fail because the remote URL does not match anymore. However, `go get -u` succeeded without errors even in this incorrect situation (because the Go package `gopkg.in/siebenmann/call.v0` is different, even though it refers to the same underlying repository, and it should have a different import path).

So I'll have to retract what I agreed to earlier:

> I do think that gostatus should not complain if `go get -u` won't.

It seems that `go get -u` does not perform a check on whether the import path matches the expected remote URL, so I'm glad that `gostatus` catches such situations.

I'm still open to consider checking for remote URL equality while ignoring the schema (as long as it's valid), but I just wanted to share the finding above first.

**Comment by shurcooL** [comment]
One observation about doing that is that it adds complexity, since simply trimming the scheme isn't enough, otherwise `github.com/siebenmann/call` will not match `github.com:siebenmann/call` because of the colon vs slash difference.

**Comment by siebenmann** [comment]
Both are useful observations (and I hadn't realized 'go get' was so liberal with existing repos, although I suppose it makes sense). Maybe the model to adopt is to split the repo upstream apart into scheme, host, and path on host, and then reassemble the whole thing in some canonical form. This would provide a natural spot and way to drop the scheme and turn 'github.com:' to 'github.com/'.

**Comment by eduncan911** [comment]
Btw, this observation is incorrect:

>It seems that go get -u does not perform a check on whether the import path matches the expected remote URL

Actually, it does -  but only if the author of the package specifies the check like so:

    package pdf // import "rsc.io/pdf"

This will cause `go get` to fail if the url does not match.  But, the vast majority of authors out there do not enforce this.  And therefore, no errors.

Is there a way we can just suppress this information?  Because we know it works and we know it matches.

**Comment by kjk** [comment]
Too lazy to do proper PR, I've implemented one case to consider `git@github.com:foo/bar.git` and `https://github.com/foo/bar` to be the same: https://github.com/kjk/gostatus/commit/d7e140913a7a3e572398f993318ea561d0924e5f

**Comment by shurcooL** [comment]
Sorry for the delay getting to this @siebenmann, but I've finally done this. Thanks for an implementation to look at @kjk.

With 8100e2558a8935b60ee906647ed6e2ddcd456fb3, this should be resolved. It now compares repo URLs ignoring the scheme and userinfo. Please let me know if there any issues.
