### ISSUE TITLE
Print something when there's nothing to report

### ISSUE THREAD

**Issue by kjk** [shurcooL/gostatus#35]
Currently in default verbose mode when there is nothing to report, nothing is printed. That gives the impression that the program didn't work at all.

Instead  it could print something like:
```
github.com/kjk/gostatus/...
	This checkout is up to date!
```

**Comment by shurcooL** [comment]
Take a look at https://github.com/shurcooL/gostatus/issues/29#issuecomment-219237760, it's somewhat relevant.

With that change, repos with no outstanding status would have all spaces in front (rather than any symbols).

**Comment by shurcooL** [comment]
I've implemented https://github.com/shurcooL/gostatus/issues/29#issuecomment-219237760, so now repos with no outstanding status (in verbose mode) have spaces instead of status symbols.

Also, `gostatus` tries to follow Unix principles of having no output and 0 exit code when things are okay, and having output when there's something to report. It exists with non-zero exit code when there's a problem.

Hopefully that resolves this issue, but let me know if not.
